select:
  global:
    num_replicates: 5
    num_train_samples:
      start : 100
      stop : 400
      step : 100
    num_test_samples: 400

    models:
      -
        model: knn
        feature_indices: [1,2,3]
        hyperparameters:
          k : 4
      -
        model: svm
        feature_indices: [1,2,3]
        hyperparameters:
          C : 1
          gamma : 0.01

  todo_list:
    - #1
      feature_file : C:\Data\gy6gy6\extract_output_170516_1935\summary_feature_file_created_170516_1935
      output_dir: C:\Data\gy6gy6\