predict:
  todo_list:
    - #1
      bird_ID: gr41rd51
      model_file : C:\Data\gy6gy6\extract_output_170519_1246select_output_170519_1323\svm\svm_400samples_replicate3
      file_format: evtaf
      data_dirs:
        - C:\Data\gy6gy6\010417
        - C:\Data\gy6gy6\010517