select:
  global:
    num_replicates: 5
    num_samples:
      start : 100
      stop : 1000
      step : 100

    models:
      -
        model: knn
        feature_indices: 1,2,3
        hyperparameters:
          n : 4
      -
        model: svm
        feature_indices: 1,2,3
        hyperparameters:
          C : 1
          gamma : 0.01

  todo_list:
    - #1
      feature_file : C:\Data\gy6gy6\extract_output_170512_2009\summary_feature_file_created_170512_2009
      output_dir: C:\Data\gy6gy6\