extract:
  spect_params:
      samp_freq: 32000 # Hz
      nperseg: 512
      noverlap: 480
      freq_cutoffs: [1000,8000]

  todo_list:
    -
      bird_ID : bl26lb16
      file_format: evtaf
      feature_group:
        - svm
      data_dirs:
        - C:\Data\bl26lb16\041912
        - C:\Data\bl26lb16\042012

      output_dir: C:\Data\bl26lb16\

      labelset: iabcdef