extract:
  spect_params:
      samp_freq: 32000 # Hz
      nperseg: 512
      noverlap: 480
      freq_cutoffs: [1000,8000]

  todo_list:
    -
      bird_ID : bl26lb16
      file_format: evtaf
      feature_group:
        - svm
        - knn
      data_dirs:
        - C:\Data\gy6gy6\010217
        - C:\Data\gy6gy6\010317

      output_dir: C:\Data\gy6gy6\

      labelset: iabcdef